spring.application.name=course-management-system

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5434/course_management_db
spring.datasource.username=postgres
spring.datasource.password=19052004

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

